---
- name: play 1 for db servers
  hosts: db
  tasks:
    - name: Installing httpd
      yum:
        name: httpd
        state: present

    - name: Installing nginx
      yum:
        name: nginx
        state: present

- name: play 2 for web servers
  hosts: web
  tasks:
    - name: Task1 for installing httpd
      yum:
        name: httpd
        state: present

    - name: Task2 for removing httpd
      yum:
        name: httpd
        state: absent


