---
- name: play to work on import tasks
  hosts: all
  vars:
    dest_path: /var/www/html/index.html
  vars_prompt:
    - name: package
      prompt: "Provide package which you want to install httpd/nginx"

    - name: state
      prompt: "provide state: latest/present/absent"
  tasks:
    - name: task to install httpd
      import_tasks: tasks/install.yml

    - name: copying web content
      import_tasks: tasks/content.yml

