---
- name: play to create users using list
  hosts: all
  vars_files:
    - userlist
  tasks:
    - name: user create
      user:
        name: "{{ item.username }}"
        shell: "{{ item.shell }}"
        comment: "{{ item.comment }}"
      loop: "{{ userlist }}"
