---
- name: play
  hosts: all
  tasks:
    - name: collect service facts
      service_facts:

    - name: fetch service state
      service:
        name: nginx
        state: started
      when: ansible_facts['services']['httpd.service']['status'] == "inactive" 
