---
- name: play for user password
  hosts: all
  vars_prompt:
    - name: username
      prompt: Please enter your name
      private: false

    - name: pass
      prompt: Please enter pssword
      private: true
  tasks:
    - name: user task
      user:
        name: "{{username}}"
        password: "{{ '{{pass}}' | password_hash('sha512') }}"
