- name: install web server based on OS_family
  hosts: servers
  tasks: 
    - name: install httpd if RedHat family OS
      yum:
        name: httpd
        state: latest
      when: ansible_os_family == "RedHat"

    - name: install httpd if Debian family OS
      yum:
        name: httpd
        state: latest
      when: ansible_os_family == "Debian"
